### ISSUE TITLE
extra nonce2's size is NOT 8 bytes

### ISSUE THREAD

**Issue by savanahmclaughlinzaz** [btccom/btcagent#3]
./agent -c agent_conf.json -l log_btcagent
F1129 21:51:49.026087 11402 Server.cc:710] extra nonce2's size is NOT 8 bytes
*** Check failure stack trace: ***
    @     0x7f315f86cbcd  google::LogMessage::Fail()
    @     0x7f315f86eb48  google::LogMessage::SendToLog()
    @     0x7f315f86c763  google::LogMessage::Flush()
    @     0x7f315f86f47e  google::LogMessageFatal::~LogMessageFatal()
    @           0x409b65  UpStratumClient::handleStratumMessage()
    @           0x40a3b2  StratumServer::upReadCallback()
    @     0x7f315f6342ea  bufferevent_readcb
    @     0x7f315f629a10  event_base_loop
    @           0x40b1a2  StratumServer::setup()
    @           0x40524e  main
    @     0x7f315ea55f45  __libc_start_main
    @           0x40554f  (unknown)
Aborted (core dumped)

I am having very similar error for running btcpool as well

**Comment by jabiers** [comment]
same issue

**Comment by YihaoPeng** [comment]
BTCAgent can only be connected to the stratum server of the [BTCPool](https://github.com/btccom/btcpool) project, and its extra nonce2's size will be 8 bytes.

It doesn't make sense to connect to other pool's server. Because they do not support the [BTCAgent protocol](https://github.com/btccom/btcpool/blob/master/docs/AGENT.md).

**Comment by yuribasketasia** [comment]
How to solve this?
#issue-192414020
